# Generated by Django 5.0 on 2023-12-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='сourses/', verbose_name='Превью')),
                ('description', models.CharField(max_length=550, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название урока')),
                ('description', models.CharField(max_length=550, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson/', verbose_name='Превью')),
                ('link', models.CharField(max_length=350, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
